### ISSUE TITLE
[Bug] hideDisabled is not working in to_svg() function

### ISSUE THREAD

**Issue by azkasadaf** [mitre-attack/mitreattack-python#89] opened 2022-10-03 21:12 UTC
## Expected Behavior
While I was trying to generate an svg from json, I had some techniques disabled in my json file
they are expected to be hidden and not appear in the final svg but that's not how it's working so far

![image](https://user-images.githubusercontent.com/63138684/193672313-2db68d98-1390-4db0-81db-ddee221952fb.png)

## Actual Behavior
with the [default configuration](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/navlayers/README.md#svgconfig), it's showing the disabled techniques as well, also platforms and legend are not appearing in the final svg

![image](https://user-images.githubusercontent.com/63138684/193676619-423701b8-055f-44c5-9ec4-a8155fe88e49.png)

## Solution Suggestions
Possibly an issue in [here](https://github.com/mitre-attack/mitreattack-python/blob/23cb9603ac97ff28c22c6d81f99270ce0c2d3044/mitreattack/navlayers/exporters/to_svg.py#L502-L508) or [maybe here](https://github.com/mitre-attack/mitreattack-python/blob/23cb9603ac97ff28c22c6d81f99270ce0c2d3044/mitreattack/navlayers/exporters/svg_templates.py#L310)

## My layer json file
https://gist.github.com/azkasadaf/e3c6e90b6099b3d1a105fbb443771150

**Comment by clemiller** [comment] 2022-12-06 21:30
This issue was addressed in PR #95. Let us know if you still run into any problems.

**Comment by azkasadaf** [comment] 2022-12-07 08:20
Hi,

I just checked the update; and it's working quite well (highly appreciate the efforts) but (sadly) it's not yet completely fixed
### Expected SVG
![image](https://user-images.githubusercontent.com/63138684/206123732-d209413d-1016-440c-9312-3fbf7d69b8af.png)
### Actual SVG
![image](https://user-images.githubusercontent.com/63138684/206123888-e40d1bc2-26c2-40e6-9739-a9806d208028.png)

- some fields are still showing in the final SVG regardless of the fact that **hideDisabled** is set to True in json config
- in addition to that the legend is not appearing if it's **NOT** pinned to the header and there is visible irregularity in the font size as well

**Comment by clemiller** [comment] 2022-12-08 13:42
Hi @azkasadaf,

Thank you for letting us know! I will look into this further. Would you be able to provide a link to the layer that is rendering incorrectly? Thanks!

**Comment by azkasadaf** [comment] 2022-12-08 14:00
sure,
thanks for the quick response!
[here](https://gist.github.com/azkasadaf/e3c6e90b6099b3d1a105fbb443771150#file-layer2-json) is the layer's json I'm using to generate the above SVG

**Comment by azkasadaf** [comment] 2023-01-19 08:45
Hi,
I wanted to ask if there is any update on the issue so far?

**Comment by clemiller** [comment] 2023-01-19 17:48
Hi @azkasadaf,

Apologies for the delay in response! The discrepancy with techniques in your SVG appears to be caused by an outdated layer file (ATT&CK v10). The techniques that are unexpectedly appearing in your SVG are techniques which have been added or modified since ATT&CK v10 (the ATT&CK version of your layer file), so it looks like the Matrix is being generated from the latest ATT&CK v12.

For example, [Serverless Execution (T1648)](https://attack.mitre.org/techniques/T1648/) is displayed because `hideDisabled` is not set in either example layer files you provided. This technique was added in ATT&CK v12.

I'd recommend upgrading your layer file to v12 or checking the ATT&CK version that is being used to generate the underlying Matrix in the [`ToSvg()`](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/navlayers/README.md#example-usage-3) function. You can download the `enterprise-attack.json` file from the [ATT&CK v10.1 Release](https://github.com/mitre/cti/releases/tag/ATT%26CK-v10.1) and use the local file to generate the underlying matrix with v10:

```python
from mitreattack.navlayers import Layer, ToSvg

lay = Layer()
lay.from_file("layer.json")

svg = ToSvg(domain='enterprise', source='local', resource='enterprise-attack-v10.1.json')
svg.to_svg(layerInit=lay, filepath="test.svg")
```

As for the issue with the legend- there is a bug in how the legend is generated when `legendDocked` is false and some inconsistency with the font sizes. We are currently working on a fix for this. The font size has been a bit of an ongoing issue in the Navigator. We've made some adjustments in the past (see [Navigator#394](https://github.com/mitre-attack/attack-navigator/pull/394)) for more consistency, but these changes have not been reflected in the Python library.

**Comment by azkasadaf** [comment] 2023-01-20 11:02
Hi @clemiller I just checked with version 12 and it's working like a charm.

![image](https://user-images.githubusercontent.com/63138684/213679650-bc603216-a585-4461-85f1-4cf0ebedf79f.png)

Although the legend is still an issue, but I guess I'll work for a while with it pinned to the header.
As for the font size I'll look into the update you've mentioned.
Thanks for the update.

**Closed** 2023-01-21 17:47 UTC
Labels: bug
